{% set name = "opendp-smartnoise-core" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/o/{{ name }}/opendp_smartnoise_core-{{ version }}-py3-none-any.whl
  sha256: cb5f7346ee52bbce409b4ce399e8db9995e6e51e8da6cea9f66e9c2f93431851

build:
  noarch: python
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed opendp_smartnoise_core-{{ version }}-py3-none-any.whl
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - protobuf >=3.11.3
    - numpy >=1.18.2
    - setuptools >=41.4.0
    - pandas >=1.0.3

test:
  imports:
    - opendp.smartnoise.core
    - opendp.smartnoise.core.api
    - opendp.smartnoise.core.base
    - opendp.smartnoise.core.components
    - opendp.smartnoise.core.value
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/opendp/smartnoise-core-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This repository contains python bindings to the SmartNoise Core library and its underlying Rust binaries.
  description: A pluggable library of differentially private algorithms and mechanisms for releasing privacy preserving queries and statistics.
  doc_url: https://docs.opendp.org/en/latest/smartnoise/
  dev_url: https://github.com/opendp/smartnoise-core-python

extra:
  recipe-maintainers:
    - mxr-conda

