{% set name = "opendp-smartnoise-core" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/py3/o/{{ name }}/opendp_smartnoise_core-{{ version }}-py3-none-any.whl
  sha256: b8b4f90fc6b9982b9f45daa4473344f96e90429176aec3e828fb956225a15db4

build:
  noarch: python
  number: 1
  script:
    - python -m pip install --no-deps --ignore-installed opendp_smartnoise_core-{{ version }}-py3-none-any.whl
  missing_dso_whitelist:
    - '*'

requirements:  
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - protobuf >=3.11.3
    - numpy >=1.18.2
    - setuptools >=41.4.0
    - pandas >=1.0.3
    
test:
  imports:
    - opendp.smartnoise.core
    - opendp.smartnoise.core.api
    - opendp.smartnoise.core.base
    - opendp.smartnoise.core.components
    - opendp.smartnoise.core.value 
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/opendp/smartnoise-core-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'This repository contains python bindings to the SmartNoise Core library and its underlying Rust binaries.'
  description: A pluggable library of differentially private algorithms and mechanisms for releasing privacy preserving queries and statistics.
  doc_url: https://docs.opendp.org/en/latest/smartnoise/
  dev_url: https://github.com/opendp/smartnoise-core-python

extra:
  recipe-maintainers:
    - mxr-conda
    
